/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frtransdavand;

import clases.buses;
import clases.viajes;
import clases.chofer;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.LogicaDeNegocio;
import modelo.conexion;

/**
 *
 * @author w7
 */
public class MainMenu extends javax.swing.JFrame {

    ArrayList<viajes> viaje;
    ArrayList<chofer> chofer;
    ArrayList<buses> bbus;

    LogicaDeNegocio coni = new LogicaDeNegocio();
    chofer cono = new chofer();
    viajes cone = new viajes();
    buses conu = new buses();

    public MainMenu() {
        initComponents();

    }

    public void ListarDatos() throws ClassNotFoundException {
        viaje = cone.ListViajes();
        DefaultTableModel tb = (DefaultTableModel) TablaViaje.getModel();
        for (viajes ch : viaje) {
            tb.addRow(new Object[]{ch.getNombre(), ch.getCedula(), ch.getPlaca(), ch.getFecha_v(), ch.getRuta_codigo_r(), ch.getMun_origen(), ch.getMun_destino()});

        }
    }

    public void ListarChofer() throws ClassNotFoundException {
        chofer = cono.LisChofer();
        DefaultTableModel tb = (DefaultTableModel) TablaChofer.getModel();
        for (chofer ch : chofer) {
            tb.addRow(new Object[]{ch.getCedula(), ch.getNombre(), ch.getApellido1(), ch.getApellido2(), ch.getCelular()});

        }
    }

    
    public void Listarbus() throws ClassNotFoundException {
        bbus = conu.LisBuses();
        DefaultTableModel tb = (DefaultTableModel) TablaBus.getModel();
        for (buses bs : bbus) {
            tb.addRow(new Object[]{bs.getPlaca(), bs.getMarca()});

        }
    }
    
    public void LimpiarFormulario() {
        DefaultTableModel tb = (DefaultTableModel) TablaViaje.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }

    }

    public void LimpiarFo() {
        DefaultTableModel tb = (DefaultTableModel) TablaChofer.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FICHOFER = new javax.swing.JFrame();
        INombrech = new javax.swing.JTextField();
        IApellido1 = new javax.swing.JTextField();
        IApellido2 = new javax.swing.JTextField();
        ICedula = new javax.swing.JTextField();
        ICelular = new javax.swing.JTextField();
        LABEL = new javax.swing.JLabel();
        LABEL2 = new javax.swing.JLabel();
        LABEL3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        insertarchofer = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        LContrasena = new javax.swing.JPasswordField();
        VERCH = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaChofer = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ELCHOFER = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        bteliminarchofer = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        eliminarchofer = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        VERBS = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaBus = new javax.swing.JTable();
        consultica = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        BExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaViaje = new javax.swing.JTable();
        BCons = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BInsert = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TPlaca = new javax.swing.JTextField();
        TRuta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ETCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bteliminar = new javax.swing.JButton();
        EFecha = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        CHOFERES = new javax.swing.JMenu();
        ICHOFER = new javax.swing.JMenuItem();
        verchofers = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        BUSES = new javax.swing.JMenu();
        IBUS = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        FICHOFER.setMinimumSize(new java.awt.Dimension(600, 250));
        FICHOFER.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                FICHOFERWindowOpened(evt);
            }
        });
        FICHOFER.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FICHOFER.getContentPane().add(INombrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 52, 92, -1));
        FICHOFER.getContentPane().add(IApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 102, 92, -1));
        FICHOFER.getContentPane().add(IApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 92, -1));
        FICHOFER.getContentPane().add(ICedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, -1));
        FICHOFER.getContentPane().add(ICelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 90, -1));

        LABEL.setText("NOMBRE: ");
        FICHOFER.getContentPane().add(LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 52, -1, -1));

        LABEL2.setText("APELLIDO1: ");
        FICHOFER.getContentPane().add(LABEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, -1, -1));

        LABEL3.setText("APELLIDO2: ");
        FICHOFER.getContentPane().add(LABEL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel17.setText("CEDULA: ");
        FICHOFER.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel18.setText("CELULAR:");
        FICHOFER.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel12.setText("INSERTAR CHOFER");
        FICHOFER.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 24, -1, 21));

        insertarchofer.setText("INSERTAR");
        insertarchofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarchoferActionPerformed(evt);
            }
        });
        FICHOFER.getContentPane().add(insertarchofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel16.setText("CONTRASEÑA:");
        FICHOFER.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        FICHOFER.getContentPane().add(LContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 90, -1));

        VERCH.setMinimumSize(new java.awt.Dimension(600, 300));

        TablaChofer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "cedula", "nombre", "Apellido1", "Apellido2", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaChofer);
        if (TablaChofer.getColumnModel().getColumnCount() > 0) {
            TablaChofer.getColumnModel().getColumn(2).setHeaderValue("Apellido1");
            TablaChofer.getColumnModel().getColumn(3).setHeaderValue("Apellido2");
            TablaChofer.getColumnModel().getColumn(4).setHeaderValue("Celular");
        }

        jButton3.setText("CONSULTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setText("CHOFERES ASIGNADOS");

        javax.swing.GroupLayout VERCHLayout = new javax.swing.GroupLayout(VERCH.getContentPane());
        VERCH.getContentPane().setLayout(VERCHLayout);
        VERCHLayout.setHorizontalGroup(
            VERCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VERCHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VERCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VERCHLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 389, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(VERCHLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VERCHLayout.setVerticalGroup(
            VERCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VERCHLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ELCHOFER.setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel14.setText("eliminar todos los viajes programados para él.");

        bteliminarchofer.setText("ELIMINAR");
        bteliminarchofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarchoferActionPerformed(evt);
            }
        });

        jLabel19.setText("DOCUMENTO:");

        jLabel21.setText("ELIMINAR VIAJES");

        jLabel22.setText("NOTA: Antes de despedir al chofer debe");

        javax.swing.GroupLayout ELCHOFERLayout = new javax.swing.GroupLayout(ELCHOFER.getContentPane());
        ELCHOFER.getContentPane().setLayout(ELCHOFERLayout);
        ELCHOFERLayout.setHorizontalGroup(
            ELCHOFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELCHOFERLayout.createSequentialGroup()
                .addGroup(ELCHOFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ELCHOFERLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(38, 38, 38)
                        .addComponent(eliminarchofer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ELCHOFERLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ELCHOFERLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22))
                    .addGroup(ELCHOFERLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(ELCHOFERLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bteliminarchofer)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        ELCHOFERLayout.setVerticalGroup(
            ELCHOFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELCHOFERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(ELCHOFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(eliminarchofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(bteliminarchofer)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(33, 33, 33))
        );

        VERBS.setMinimumSize(new java.awt.Dimension(387, 262));

        TablaBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "MARCA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaBus);

        consultica.setText("CONSULTAR");
        consultica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulticaActionPerformed(evt);
            }
        });

        jLabel20.setText("BUSES ASIGNADOS");

        javax.swing.GroupLayout VERBSLayout = new javax.swing.GroupLayout(VERBS.getContentPane());
        VERBS.getContentPane().setLayout(VERBSLayout);
        VERBSLayout.setHorizontalGroup(
            VERBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VERBSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VERBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VERBSLayout.createSequentialGroup()
                        .addComponent(consultica)
                        .addGap(0, 273, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(VERBSLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VERBSLayout.setVerticalGroup(
            VERBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VERBSLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BExit.setText("Salir");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario: ");

        jLabel2.setText("!!!!!!!");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablaViaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "CEDULA", "PLACA", "FECHA", "CODIGO_RUTA_R", "MUN_ORIGEN", "MUN_DESTINO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaViaje);

        BCons.setText("Consultar");
        BCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BCons)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCons)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);

        TCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCedulaActionPerformed(evt);
            }
        });

        jLabel6.setText("FECHA");

        jLabel5.setText("RUTA:");

        BInsert.setText("Insertar");
        BInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertActionPerformed(evt);
            }
        });

        BEdit.setText("Editar");

        jLabel4.setText("DOCUMENTO: ");

        TRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRutaActionPerformed(evt);
            }
        });

        jLabel3.setText("PLACA:");

        jLabel13.setText("INSERTAR VIAJES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BInsert)
                        .addGap(78, 78, 78)
                        .addComponent(BEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(TPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(TPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BInsert)
                    .addComponent(BEdit))
                .addGap(106, 106, 106))
        );

        ELIMINAR.addTab("INSERTAR", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("DOCUMENTO:");

        jLabel8.setText("FECHA:");

        jLabel9.setText("ELIMINAR VIAJES");

        jLabel10.setText("NOTA: Ingrese cedula del chofer y la fecha");

        jLabel11.setText("del viaje que desea eliminar");

        bteliminar.setText("ELIMINAR");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ETCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bteliminar)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ETCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(EFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(bteliminar)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(33, 33, 33))
        );

        ELIMINAR.addTab("ELIMINAR", jPanel3);

        CHOFERES.setText("CHOFERES");

        ICHOFER.setText("INSERTAR CHOFER");
        ICHOFER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICHOFERActionPerformed(evt);
            }
        });
        CHOFERES.add(ICHOFER);

        verchofers.setText("VER CHOFERES");
        verchofers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verchofersActionPerformed(evt);
            }
        });
        CHOFERES.add(verchofers);

        jMenuItem1.setText("DESPEDIR CHOFER");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        CHOFERES.add(jMenuItem1);

        jMenuBar2.add(CHOFERES);

        BUSES.setText("BUSES");

        IBUS.setText("INSERTAR BUS");
        IBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IBUSActionPerformed(evt);
            }
        });
        BUSES.add(IBUS);

        jMenuItem2.setText("VER BUSES");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        BUSES.add(jMenuItem2);

        jMenuBar2.add(BUSES);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BExit)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(ELIMINAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BExit)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        Login_Transportes tras = new Login_Transportes();
        tras.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BExitActionPerformed

    private void BConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsActionPerformed
        LimpiarFormulario();
        try {
            ListarDatos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BConsActionPerformed

    private void ICHOFERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICHOFERActionPerformed
        FICHOFER.setVisible(true);
    }//GEN-LAST:event_ICHOFERActionPerformed

    private void IBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IBUSActionPerformed
        insertbus bus = new insertbus();
        bus.setVisible(true);


    }//GEN-LAST:event_IBUSActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed

        String ecedula = ETCedula.getText();
        String fecha = new SimpleDateFormat("yyyy/MM/dd").format(EFecha.getDate());

        try {
            cone.eliminarRegistro(ecedula, fecha);
            ETCedula.setText("");
            EFecha.setToolTipText("");
            LimpiarFormulario();
            ListarDatos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void TRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRutaActionPerformed

    private void BInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertActionPerformed
        String cedula = TCedula.getText();
        int ruta = Integer.parseInt(TRuta.getText());
        String placa = TPlaca.getText();
        String fecha = new SimpleDateFormat("dd/MM/yyyy").format(Fecha.getDate());
        String fecha1 = new SimpleDateFormat("yyyy/MM/dd").format(Fecha.getDate());

        LogicaDeNegocio ln = new LogicaDeNegocio();
        if (!ln.validarSiExistevj(cedula, ruta, placa, fecha1)) {
              if (ln.validarSiExistech(cedula)) {
                 cone.insertar(cedula, ruta, placa, fecha);
                  TCedula.setText("");
                 TRuta.setText("");
                 TPlaca.setText("");
                  Fecha.setToolTipText("");
        

             } else {

            JOptionPane.showMessageDialog(this, "Chofer no valido, por favor revice la cedula!");

            FICHOFER.requestFocusInWindow();

            return;

            }
          

            JOptionPane.showMessageDialog(this, "viaje programado correctamente!");
        } else {

            JOptionPane.showMessageDialog(this, "error, el viaje ya está programado");

            FICHOFER.requestFocusInWindow();

            return;

        }


    }//GEN-LAST:event_BInsertActionPerformed

    private void TCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCedulaActionPerformed

    private void insertarchoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarchoferActionPerformed
        String cedula = ICedula.getText();
        String nombre = INombrech.getText();
        String celular = ICelular.getText();

        String apellido1 = IApellido1.getText();
        String apellido2 = IApellido2.getText();
        String contrasena = LContrasena.getText();

        LogicaDeNegocio ln = new LogicaDeNegocio();
        if (!ln.validarSiExistech(cedula)) {

            cono.insertarCh(cedula, nombre, apellido1, apellido2, celular);
            cono.insertarchlg(cedula, contrasena);

        } else {

            JOptionPane.showMessageDialog(this, "Chofer ya existe");

            FICHOFER.requestFocusInWindow();

            return;

        }


    }//GEN-LAST:event_insertarchoferActionPerformed

    private void verchofersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verchofersActionPerformed
        VERCH.setVisible(true);
    }//GEN-LAST:event_verchofersActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            LimpiarFo();
            ListarChofer();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FICHOFERWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FICHOFERWindowOpened


    }//GEN-LAST:event_FICHOFERWindowOpened

    private void bteliminarchoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarchoferActionPerformed
        String cedula = eliminarchofer.getText();
        LogicaDeNegocio ln = new LogicaDeNegocio();
        if (!ln.validarSiExistech(cedula)) {

            JOptionPane.showMessageDialog(this, "ERROR, CHOFER NO EXISTE");

        } else {

            try {
                cono.eliminarRegistrologin(cedula);
                cono.eliminarRegistro(cedula);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_bteliminarchoferActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ELCHOFER.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void consulticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulticaActionPerformed
           try {

            
            Listarbus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_consulticaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    VERBS.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCons;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BExit;
    private javax.swing.JButton BInsert;
    private javax.swing.JMenu BUSES;
    private javax.swing.JMenu CHOFERES;
    private com.toedter.calendar.JDateChooser EFecha;
    private javax.swing.JFrame ELCHOFER;
    private javax.swing.JTabbedPane ELIMINAR;
    private javax.swing.JTextField ETCedula;
    private javax.swing.JFrame FICHOFER;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JTextField IApellido1;
    private javax.swing.JTextField IApellido2;
    private javax.swing.JMenuItem IBUS;
    private javax.swing.JMenuItem ICHOFER;
    private javax.swing.JTextField ICedula;
    private javax.swing.JTextField ICelular;
    private javax.swing.JTextField INombrech;
    private javax.swing.JLabel LABEL;
    private javax.swing.JLabel LABEL2;
    private javax.swing.JLabel LABEL3;
    private javax.swing.JPasswordField LContrasena;
    private javax.swing.JTextField TCedula;
    private javax.swing.JTextField TPlaca;
    private javax.swing.JTextField TRuta;
    private javax.swing.JTable TablaBus;
    private javax.swing.JTable TablaChofer;
    private javax.swing.JTable TablaViaje;
    private javax.swing.JFrame VERBS;
    private javax.swing.JFrame VERCH;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton bteliminarchofer;
    private javax.swing.JButton consultica;
    private javax.swing.JTextField eliminarchofer;
    private javax.swing.JButton insertarchofer;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem verchofers;
    // End of variables declaration//GEN-END:variables
}
